// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void handleExposureValueChange(lv_event_t * e);
void handleExposureChangeSetBreakTime(lv_event_t * e);
void handleBreakTimeValueChange(lv_event_t * e);
void handleMaxOnTimeChangeSetBreakTime(lv_event_t * e);
void handleStartStop(lv_event_t * e);
void handleYes(lv_event_t * e);
void handleNo(lv_event_t * e);
void handleMakeCheckMarkWork(lv_event_t * e);
void handleKeyboardIssue(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
