// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

// void handleExposureValueChange(lv_event_t * e)
// {
// 	// Your code here
// }

// void handleStart(lv_event_t * e)
// {
// 	// Your code here
// }

// void handleStop(lv_event_t * e)
// {
// 	// Your code here
// }
