// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelExposureTime = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelExposureTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelExposureTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelExposureTime, -152 );
lv_obj_set_y( ui_LabelExposureTime, -79 );
lv_obj_set_align( ui_LabelExposureTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelExposureTime,"Exposure Time:");

ui_LabelBreakTime = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelBreakTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBreakTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBreakTime, -160 );
lv_obj_set_y( ui_LabelBreakTime, 3 );
lv_obj_set_align( ui_LabelBreakTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBreakTime,"Break Time:");

ui_TextAreaExposureTime = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextAreaExposureTime, 150);
lv_obj_set_height( ui_TextAreaExposureTime, 30);
lv_obj_set_x( ui_TextAreaExposureTime, -11 );
lv_obj_set_y( ui_TextAreaExposureTime, -83 );
lv_obj_set_align( ui_TextAreaExposureTime, LV_ALIGN_CENTER );
if ("1,2,3,4,5,6,7,8,9,0"=="") lv_textarea_set_accepted_chars(ui_TextAreaExposureTime, NULL);
else lv_textarea_set_accepted_chars(ui_TextAreaExposureTime, "1,2,3,4,5,6,7,8,9,0");
lv_textarea_set_placeholder_text(ui_TextAreaExposureTime,"Enter in seconds");



ui_TextAreaBreakTime = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextAreaBreakTime, 150);
lv_obj_set_height( ui_TextAreaBreakTime, 28);
lv_obj_set_x( ui_TextAreaBreakTime, -16 );
lv_obj_set_y( ui_TextAreaBreakTime, 3 );
lv_obj_set_align( ui_TextAreaBreakTime, LV_ALIGN_CENTER );
if ("1,2,3,4,5,6,7,8,9,0"=="") lv_textarea_set_accepted_chars(ui_TextAreaBreakTime, NULL);
else lv_textarea_set_accepted_chars(ui_TextAreaBreakTime, "1,2,3,4,5,6,7,8,9,0");
lv_textarea_set_placeholder_text(ui_TextAreaBreakTime,"Enter in seconds");



ui_LabelTotalTime = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelTotalTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTotalTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTotalTime, -81 );
lv_obj_set_y( ui_LabelTotalTime, -131 );
lv_obj_set_align( ui_LabelTotalTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTotalTime,"Total Time:");

ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 466);
lv_obj_set_height( ui_Keyboard1, 120);
lv_obj_set_x( ui_Keyboard1, -3 );
lv_obj_set_y( ui_Keyboard1, 87 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_LabelMaxOnTime = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelMaxOnTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxOnTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxOnTime, -156 );
lv_obj_set_y( ui_LabelMaxOnTime, -37 );
lv_obj_set_align( ui_LabelMaxOnTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxOnTime,"Max On Time:");

ui_TextAreaMaxOnTime = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextAreaMaxOnTime, 150);
lv_obj_set_height( ui_TextAreaMaxOnTime, 29);
lv_obj_set_x( ui_TextAreaMaxOnTime, -12 );
lv_obj_set_y( ui_TextAreaMaxOnTime, -39 );
lv_obj_set_align( ui_TextAreaMaxOnTime, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaMaxOnTime,"Enter in seconds");



ui_TextArea4 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea4, 150);
lv_obj_set_height( ui_TextArea4, 30);
lv_obj_set_x( ui_TextArea4, 47 );
lv_obj_set_y( ui_TextArea4, -131 );
lv_obj_set_align( ui_TextArea4, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea4,"TempVal");
lv_textarea_set_placeholder_text(ui_TextArea4,"Will be updated");



ui_ButtonStart = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_ButtonStart, 100);
lv_obj_set_height( ui_ButtonStart, 50);
lv_obj_set_x( ui_ButtonStart, -150 );
lv_obj_set_y( ui_ButtonStart, 98 );
lv_obj_set_align( ui_ButtonStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelStart = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelStart, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStart, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStart, -151 );
lv_obj_set_y( ui_LabelStart, 97 );
lv_obj_set_align( ui_LabelStart, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStart,"Start");

ui_ButtonStop = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_ButtonStop, 100);
lv_obj_set_height( ui_ButtonStop, 50);
lv_obj_set_x( ui_ButtonStop, -26 );
lv_obj_set_y( ui_ButtonStop, 97 );
lv_obj_set_align( ui_ButtonStop, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonStop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelStop = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelStop, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStop, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStop, -28 );
lv_obj_set_y( ui_LabelStop, 98 );
lv_obj_set_align( ui_LabelStop, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStop,"Stop");

lv_obj_add_event_cb(ui_TextAreaExposureTime, ui_event_TextAreaExposureTime, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaBreakTime, ui_event_TextAreaBreakTime, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaMaxOnTime, ui_event_TextAreaMaxOnTime, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonStart, ui_event_ButtonStart, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonStop, ui_event_ButtonStop, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
